dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - master
    - /^release\-.+/

script:
  - mntdir='/mnt/ocs-url'
  - docker run --rm -v $(pwd):${mntdir} ubuntu:14.04 /bin/bash -c "${mntdir}/scripts/package ubuntu_deb"
  - docker run --rm -v $(pwd):${mntdir} fedora:20 /bin/bash -c "${mntdir}/scripts/package fedora_rpm"
  - docker run --rm -v $(pwd):${mntdir} opensuse:42.1 /bin/bash -c "${mntdir}/scripts/package opensuse_rpm"
  - docker run --rm -v $(pwd):${mntdir} base/archlinux:latest /bin/bash -c "${mntdir}/scripts/package archlinux_pkg"
  - cat transfer.log
